(function () {
  "use strict";

  const answersByPage = {
    "linux-foundations.html": [
      "Linux is an open-source, Unix-like operating-system kernel. In everyday use, the name also refers to complete distributions built from that kernel plus user-space tools and applications.",
      "The Linux kernel is the privileged core of the operating system. It manages processes, CPU scheduling, memory, devices, filesystems, networking and security, and exposes these services through system calls.",
      "Kernel space has unrestricted access to hardware and protected memory. User-space programs run with limited privileges and request kernel services through controlled system calls.",
      "A Linux distribution packages the kernel with libraries, tools, a package manager, defaults and support. Ubuntu, Debian, RHEL and Fedora are examples.",
      "/etc stores system-wide configuration, such as service settings, user databases and startup configuration. It should contain configuration rather than ordinary application data.",
      "/var stores data that changes while the system runs, including logs, caches, queues, databases, mail spools and application state.",
      "/proc is a virtual view of processes and kernel state; /sys exposes devices, drivers and kernel objects. They are generated by the kernel and are not normal on-disk filesystems.",
      "An absolute path starts at / and identifies the same location regardless of the current directory. A relative path is resolved from the current working directory.",
      "An inode stores filesystem metadata such as owner, permissions, timestamps and pointers to data blocks. A directory entry maps a filename to an inode number.",
      "A hard link is another name for the same inode and normally cannot cross filesystems. A symbolic link is a separate file containing a path, can cross filesystems and can become broken.",
      "Use file PATH for a content-based type check and ls -l for the directory-entry type and permissions. stat provides detailed metadata.",
      "Start with COMMAND --help, then man COMMAND. Use apropos KEYWORD or man -k KEYWORD when you know the task but not the command name."
    ],

    "boot-process.html": [
      "Firmware initializes hardware, GRUB loads the kernel and initramfs, the kernel initializes drivers and mounts the root filesystem, then PID 1—usually systemd—starts units until the configured target is reached.",
      "BIOS is legacy firmware that initializes hardware and loads boot code, traditionally from a disk's master boot record.",
      "UEFI is the modern firmware interface. It can load EFI applications from an EFI System Partition and supports features such as Secure Boot and GPT disks.",
      "GRUB is a bootloader. It presents boot choices, loads the selected kernel and initramfs into memory, and passes kernel command-line parameters.",
      "initramfs is a temporary early userspace loaded into memory. It contains the tools and drivers needed to discover and mount the real root filesystem.",
      "The kernel initializes memory, CPU scheduling, drivers and filesystems, starts the first userspace process, and hands control to PID 1 to start the rest of the system.",
      "PID 1 is responsible for bringing up userspace and adopting orphaned processes. systemd also manages dependencies, service supervision, targets and shutdown.",
      "A systemd unit is a resource described by a unit file, such as a service, socket, mount, timer, target or device.",
      "A target groups units to represent a system state or synchronization point, such as multi-user.target or rescue.target.",
      "systemctl start launches a unit now. systemctl enable creates the links that make it start automatically when its required target is reached.",
      "Active describes the unit's current runtime state. Enabled describes whether it is configured to start automatically; a unit can be active but disabled, or enabled but currently inactive.",
      "systemctl daemon-reload makes systemd reread unit files and rebuild its dependency information after a unit file or drop-in changes. It does not restart the service.",
      "Run systemctl --failed, then inspect a unit with systemctl status UNIT and journalctl -u UNIT -b.",
      "journalctl -b shows logs for the current boot. Add -p warning for higher-priority messages or -u UNIT for one service.",
      "journalctl -b -1 shows the previous boot when persistent journal data is available. journalctl --list-boots lists recorded boots.",
      "Use systemd-analyze, systemd-analyze blame and systemd-analyze critical-chain, then confirm delays in the journal instead of assuming the slowest-listed unit is the root cause.",
      "Rescue mode starts a minimal system with essential mounts and services plus a maintenance shell. It is useful when normal multi-user startup fails.",
      "Emergency mode provides an even smaller environment, often with the root filesystem read-only and very few units started. It is intended for serious boot or filesystem repair.",
      "Check systemctl --failed, the service's enabled state and journalctl -u SERVICE -b. Then verify dependencies such as mounts, network readiness, secrets and environment, and compare boot-time startup with a manual start.",
      "Check last -x, journalctl --list-boots and the end of the previous boot with journalctl -b -1 -e. Correlate kernel, power, watchdog, OOM and hypervisor or cloud events before deciding the cause."
    ],

    "storage.html": [
      "A block device exposes fixed-size addressable blocks for storage I/O. Disks, partitions, logical volumes and some virtual devices appear as block devices under /dev.",
      "A disk is the whole physical or virtual storage device. A partition is a defined region of that disk represented as a separate block device.",
      "MBR is older, has limited partitioning and disk-size support, and stores boot information in the first sector. GPT supports large disks, many partitions and redundant metadata, and is standard with UEFI.",
      "A filesystem organizes files, directories and metadata on a block device. Examples include ext4, XFS and Btrfs.",
      "A mount point is a directory where a filesystem is attached to the single Linux directory tree and becomes accessible.",
      "/etc/fstab defines filesystems that should be mounted automatically, including the source, mount point, type, options and fsck order.",
      "A UUID identifies a filesystem independently of changing device names such as /dev/sdb. This makes boot-time mounts more stable.",
      "df reports used and available blocks from filesystem metadata. du walks visible files and sums their sizes, so deleted-open files, mount boundaries, sparse files and permissions can make the numbers differ.",
      "An inode stores a file's metadata and data-block pointers. A filesystem can run out of inodes even while data blocks remain free.",
      "The filesystem may have no free inodes, reserved blocks may be unavailable to the user, or a quota may be exhausted. Check df -i, quotas and the exact filesystem containing the target path.",
      "Common causes are deleted files still held open, files hidden beneath a mount, permissions that prevent du from reading paths, and filesystem-reserved space. Use lsof +L1 and confirm mount boundaries.",
      "lsof +L1 finds open files whose link count is below one—usually files deleted from the directory tree but still consuming space until the process closes them.",
      "Swap is disk-backed virtual memory used to move less-active pages out of RAM. It can provide headroom but is far slower than RAM and is not a substitute for sufficient memory.",
      "LVM is a flexible storage abstraction that combines physical volumes into volume groups and allocates logical volumes that can be resized or snapshotted.",
      "A Physical Volume is a disk, partition or other block device initialized for use by LVM.",
      "A Volume Group is a pool of storage capacity created from one or more physical volumes.",
      "A Logical Volume is a virtual block device allocated from a volume group and normally formatted with a filesystem or used as swap.",
      "RAID combines multiple devices for performance, availability or both. Common levels include RAID 0, 1, 5, 6 and 10.",
      "RAID only protects against some device failures. It does not protect against deletion, corruption, malware, controller failure or a site disaster, so independent tested backups are still required.",
      "NFS is a network filesystem protocol that lets a server export directories for remote clients to mount and access.",
      "Use mount -av to reproduce the error, validate /etc/fstab, resolve UUIDs with blkid, confirm the mount point and filesystem health, and inspect journalctl -b. For remote mounts also verify network and name resolution.",
      "Confirm the affected filesystem with df -hT and df -i, locate usage without crossing filesystems, inspect logs and deleted-open files, and identify growth before deleting anything. Rotate or archive data safely and prevent recurrence."
    ],

    "processes.html": [
      "A process is a running instance of a program with its own PID, memory mappings, file descriptors, credentials and execution state.",
      "PID is the numeric Process ID used by the kernel and tools to identify a running process.",
      "PPID is the parent process ID. It shows which process created or currently parents another process.",
      "ps provides a point-in-time process snapshot that is easy to filter and script. top provides a continuously refreshed interactive view of processes and system activity.",
      "Common states include R running or runnable, S interruptible sleep, D uninterruptible I/O sleep, T stopped or traced, and Z zombie.",
      "SIGTERM asks a process to terminate gracefully, giving it a chance to clean up and flush data. kill sends SIGTERM by default.",
      "SIGKILL immediately asks the kernel to terminate a process and cannot be caught or ignored. It prevents application cleanup.",
      "SIGKILL can leave incomplete work, stale state or recovery activity. Start with the application's normal stop mechanism or SIGTERM, wait, and use SIGKILL only when necessary.",
      "SIGHUP traditionally indicates a terminal hangup, but many daemons use it to reload configuration or reopen logs. The exact behavior is application-specific.",
      "A zombie is an exited process whose parent has not yet collected its exit status. It consumes a process-table entry but no running CPU or normal memory.",
      "An orphan is a running process whose parent exited. PID 1 or a designated subreaper adopts it so its final status can later be collected.",
      "nohup makes a command ignore SIGHUP and redirects output when needed, allowing it to continue after the terminal closes. It is not a service supervisor.",
      "nice sets a process's scheduling niceness at launch. A higher nice value usually gives it lower CPU scheduling priority.",
      "renice changes the niceness of an existing process, subject to permissions and allowed priority limits.",
      "Use top or ps -eo pid,ppid,cmd,%cpu --sort=-%cpu, confirm the usage over time, and inspect the responsible process, threads, logs and workload.",
      "Use ps -eo pid,ppid,cmd,%mem,rss --sort=-rss or top, then distinguish RSS growth from cache and inspect application metrics or mappings.",
      "Use lsof -p PID or inspect /proc/PID/fd. The latter exposes symbolic links for every open file descriptor.",
      "/proc is a virtual filesystem exposing process and kernel information. Each /proc/PID directory contains status, command line, mappings, file descriptors and other runtime data.",
      "D means uninterruptible sleep, usually while waiting for kernel I/O. The process often cannot handle signals until the wait completes, so investigate storage, NFS, device and kernel messages.",
      "Check the service restart policy and journal, record exit codes and signals, validate configuration and dependencies, and inspect OOM or health-check failures. Fix the cause before disabling supervision.",
      "An unlinked file remains allocated while any process keeps its file descriptor open. Use lsof +L1, then restart or signal the owning process safely so it closes or reopens the file."
    ],

    "permissions.html": [
      "UID 0 is the superuser identity. The kernel grants it broad privileges, so access to root must be tightly controlled and audited.",
      "A UID identifies a user account; a GID identifies a group. File ownership and process credentials use these numeric IDs.",
      "/etc/passwd stores account metadata such as username, UID, primary GID, home directory and login shell. Password hashes are normally stored separately in /etc/shadow.",
      "/etc/shadow contains password hashes and ageing information. It is restricted because exposed hashes can be attacked offline.",
      "A primary group is the default GID recorded for a user and normally applied to newly created files unless directory rules change it.",
      "Supplementary groups grant a user additional group memberships and access beyond the primary group.",
      "chmod 755 gives the owner read, write and execute permissions, while group and others get read and execute permissions.",
      "chmod 640 gives the owner read and write, the group read-only, and others no permission.",
      "chmod changes permission bits. chown changes the owning user and optionally the owning group.",
      "Execute permission on a directory allows traversal and access to known entries. Listing names requires read permission, while creating or deleting entries usually requires write plus execute.",
      "umask removes permission bits from the default mode used for new files and directories. For example, 022 typically produces 644 files and 755 directories.",
      "sudo runs an authorized command as another user, usually root, according to sudoers policy. It supports least privilege and records use.",
      "visudo locks the policy file and validates its syntax before installation, reducing the risk of breaking all sudo access.",
      "An Access Control List adds permissions for specific users or groups beyond the traditional owner, group and other mode bits. Use getfacl and setfacl to inspect and manage it.",
      "SetUID on an executable makes it run with the file owner's effective UID. It is powerful and should be used only on trusted, carefully reviewed binaries.",
      "SetGID on an executable applies the file's group as the effective GID. On a directory, it makes new entries inherit the directory's group.",
      "The sticky bit on a shared writable directory prevents users from deleting or renaming entries they do not own. /tmp commonly uses it.",
      "Identify the process user, use namei -l on the full path, inspect ls -l and getfacl, and check mount options plus SELinux or AppArmor denials. Fix the smallest incorrect layer.",
      "Every parent directory requires execute permission for traversal. ACLs, SELinux or AppArmor, a read-only or noexec mount, immutable attributes and the process's actual identity can also deny access.",
      "Running as a dedicated unprivileged account limits the damage from a compromised service, improves isolation and makes ownership and auditing clearer. Grant only required permissions or capabilities."
    ],

    "networking.html": [
      "An IP address identifies a network interface at the Internet layer so packets can be routed to and from it. IPv4 uses 32-bit addresses and IPv6 uses 128-bit addresses.",
      "/24 means the first 24 IPv4 bits are the network prefix, equivalent to netmask 255.255.255.0. It leaves 8 bits for addresses within that subnet.",
      "A subnet is a range of IP addresses sharing a network prefix. Hosts use the prefix to decide whether a destination is local or must be reached through a router.",
      "A default gateway is the next-hop router used when no more-specific route matches a destination.",
      "A routing table maps destination prefixes to next hops, interfaces and metrics. The kernel chooses the most specific matching route for each packet.",
      "Use ip route and ip -6 route. ip route get DESTINATION shows the exact route, source address and interface the kernel would select.",
      "TCP is connection-oriented and provides ordered, reliable byte delivery with retransmission, flow control and congestion control.",
      "UDP is connectionless and sends individual datagrams without guaranteeing delivery, order or duplicate protection. Applications add reliability if needed.",
      "TCP provides a reliable ordered stream and connection state; UDP has lower protocol overhead but no built-in delivery guarantee. The application requirement determines the choice.",
      "A port is a 16-bit transport-layer number used with an IP address and protocol to direct traffic to a particular service endpoint.",
      "A socket is a kernel communication endpoint described by attributes such as protocol, local address and port, and sometimes a remote peer.",
      "Use sudo ss -ltnp for TCP or sudo ss -lunp for UDP. lsof -i :PORT can provide another process view.",
      "127.0.0.1 is the IPv4 loopback address. Traffic to it stays on the local host and is not sent to an external network.",
      "A service bound to 127.0.0.1 accepts only local connections. A service bound to 0.0.0.0 accepts IPv4 connections on all local interfaces, subject to firewall and routing rules.",
      "DNS translates domain names into records such as IP addresses and also supports reverse lookups, mail routing and service discovery.",
      "/etc/hosts is a local static hostname-to-address mapping consulted according to /etc/nsswitch.conf. It can override or supplement DNS for specific names.",
      "/etc/resolv.conf describes resolver settings such as nameservers and search domains, though a manager such as systemd-resolved may generate it.",
      "Connection refused usually means the destination was reachable but no process was listening on that address and port, or a firewall actively rejected the connection.",
      "A timeout can result from dropped firewall traffic, missing routes, an unreachable host, security-group rules, an overloaded service or return-path problems.",
      "Confirm the service is listening on a non-loopback address, test curl or nc locally and via the server IP, then inspect host firewall, cloud rules, routes and reverse-proxy configuration.",
      "Test connectivity to a known IP first, then query the name with getent hosts, resolvectl query or dig. If IP access works but name lookup fails, focus on resolver configuration and DNS.",
      "Define the failing source, destination and time; test DNS, route and port; check the listener and service logs; inspect host and cloud firewalls; then trace the path and compare recent changes."
    ],

    "logs.html": [
      "Run systemctl status SERVICE and journalctl -u SERVICE -b. Add --since, --until, -p or -f to narrow by time, priority or live activity.",
      "journalctl -b shows journal entries from the current boot. Use -b -1 for the previous recorded boot.",
      "Use journalctl -f for the journal or tail -F /path/to/log for a text log. Filter to the relevant service and reproduce the event.",
      "logrotate rotates, compresses, retains and removes text logs according to policy. It prevents unlimited growth and can signal applications to reopen log files.",
      "dmesg reads the kernel ring buffer and focuses on kernel and driver messages. journalctl queries the systemd journal, which can include kernel, service and application logs with structured metadata."
    ],

    "packages.html": [
      "A Linux package is a versioned archive of software, metadata, dependencies and install or removal scripts managed by the distribution's package system.",
      "A repository is a signed, indexed source of packages and metadata from which a package manager resolves and downloads software.",
      "apt update downloads current repository indexes. It does not upgrade installed packages.",
      "apt update refreshes available package metadata; apt upgrade installs newer permitted versions of already installed packages after dependency resolution.",
      "apt is a high-level resolver that works with repositories and dependencies. dpkg is the lower-level Debian package database and installer for individual .deb files.",
      "On Debian-based systems use dpkg -s PACKAGE or apt list --installed PACKAGE. On RPM systems use rpm -q PACKAGE or dnf list installed PACKAGE.",
      "Use dpkg -S /path/to/file on Debian-based systems or rpm -qf /path/to/file on RPM-based systems.",
      "Packages declare required or optional relationships. The package manager selects compatible versions and installs dependencies from configured repositories, or reports a conflict when it cannot.",
      "Use apt policy PACKAGE or apt-cache policy PACKAGE on Debian-based systems, and dnf list --showduplicates PACKAGE on DNF-based systems.",
      "apt-cache policy shows installed and candidate versions plus the repository priority that produced each available version. It is useful for pinning and source diagnosis.",
      "apt remove uninstalls package files but usually retains system configuration. apt purge also removes package-managed configuration files; neither should be used without understanding application data locations.",
      "apt autoremove removes packages installed automatically as dependencies that are no longer required. Review the proposed list before confirming.",
      "DNF is the high-level package manager used by modern Fedora and RHEL-family systems. It handles repositories, dependencies, transactions and history.",
      "RPM is both the package format and the lower-level tool and database used to install, query and verify RPM packages.",
      "DNF resolves dependencies and repository transactions; rpm directly queries or installs RPM files with much less dependency management.",
      "Refresh metadata, verify the package name and OS release, inspect enabled repositories and architecture, then use apt policy or dnf provides/search to confirm availability.",
      "Read the exact repository error, then verify DNS, proxy, time, certificates, repository URLs and signing keys. Disable a repository only when its purpose and impact are understood.",
      "Inspect the resolver's exact conflict, verify versions and repository mixing, repair interrupted transactions, and avoid forcing or manually deleting package database files. Use a tested rollback plan in production.",
      "Review transaction history and changed dependencies, compare configuration, inspect service logs and test rollback or a known-good version. Preserve evidence before downgrading.",
      "Upgrades can change dependencies, configuration, services and data formats. Production changes need testing, backups, maintenance planning, health checks and a documented rollback path."
    ],

    "shell-scripting.html": [
      "A shebang is the first-line #! path that tells the kernel which interpreter should execute the script, for example #!/usr/bin/env bash.",
      "Assign without spaces, for example name=\"value\". Reference it as $name or ${name}, usually inside double quotes.",
      "export places a shell variable in the environment inherited by subsequently started child processes. It does not update the parent shell.",
      "$0 is the name or path used to invoke the script or shell.",
      "$1 is the first positional argument passed to a script or function.",
      "$@ expands to all positional arguments. When written as \"$@\", it preserves each argument as a separate word and is usually the safe form.",
      "$# is the number of positional arguments currently available.",
      "$? is the exit status of the most recently completed foreground command or pipeline. Zero conventionally means success.",
      "Command substitution captures a command's standard output, for example current=$(date +%F). Trailing newlines are removed.",
      "Use arithmetic tests such as (( a > b )) or test operators such as [ \"$a\" -gt \"$b\" ]. Validate that inputs are numeric first.",
      "A for loop iterates over a known list or expansion; a while loop repeats while a condition succeeds and is common for streams or condition-controlled work.",
      "Use name() { commands; } and invoke it by name. Function arguments are available through $1, $2, \"$@\" and related positional parameters.",
      "Create an indexed array with items=(one two), access ${items[0]}, all elements with \"${items[@]}\", and the length with ${#items[@]}. Bash also supports associative arrays.",
      "Quoting prevents unwanted word splitting and filename expansion, and preserves empty values. Use \"$variable\" unless you intentionally require splitting or globbing.",
      "set -e requests exit after some unhandled non-zero statuses, but its exceptions are context-dependent. Use explicit error handling for critical operations.",
      "set -u treats expansion of most unset variables as an error. Use defaults such as ${value:-default} where absence is acceptable.",
      "set -o pipefail makes a pipeline fail when any command in it fails, rather than reporting only the last command's status.",
      "trap registers code to run when the shell receives specified signals or exits. It is commonly used for cleanup, temporary-file removal and controlled termination.",
      "Run bash -n script.sh for syntax, shellcheck for static analysis when available, and bash -x script.sh or set -x for execution tracing without exposing secrets.",
      "Cron supplies a minimal environment, different PATH, no interactive shell and a different working directory. Use absolute paths, set required variables, redirect output and test as the cron user.",
      "Collect usage with df for the intended filesystem, compare it to a validated numeric threshold, emit a clear timestamped alert, return meaningful exit codes and prevent duplicate alert storms.",
      "Check required variables before use, for example : \"${DATABASE_URL:?DATABASE_URL is required}\". Validate format separately and never print secret values in errors or traces."
    ],

    "cron.html": [
      "cron is a time-based job scheduler that runs commands from user or system crontabs according to calendar expressions.",
      "Use */5 * * * * COMMAND in a crontab to run every five minutes. Add explicit paths, environment and output handling for reliability.",
      "Cron uses a minimal environment, limited PATH, no interactive shell and often a different working directory. The job may also run as a different user.",
      "Confirm the crontab and user, inspect cron service logs, redirect stdout and stderr, use absolute paths, reproduce with the same user and environment, and check permissions and locking.",
      "Cron is simple calendar scheduling. systemd timers integrate with service units, dependencies, logging, randomized delays, persistent catch-up and resource controls."
    ],

    "memory.html": [
      "Swap is disk-backed space used for inactive memory pages and emergency headroom. It is much slower than RAM and sustained heavy swapping usually indicates pressure.",
      "Linux deliberately uses otherwise-idle RAM for filesystem cache and reclaims it when applications need memory. The available value is therefore more useful than treating free alone as capacity.",
      "The OOM Killer is a kernel mechanism that selects and terminates a process when memory cannot be allocated and recovery is otherwise impossible. Check kernel logs for the victim and context.",
      "Use ps -eo pid,user,comm,rss,%mem --sort=-rss or top, then inspect the process over time. Distinguish heap growth from shared mappings and filesystem cache.",
      "Free is currently unused RAM. Available estimates how much memory can be given to new workloads without swapping by including reclaimable cache and other reclaimable pages."
    ],

    "cpu-load.html": [
      "Load average is the average number of tasks running or waiting for CPU plus tasks in uninterruptible sleep, usually I/O waits. Interpret it relative to CPU count and workload.",
      "They are the average system load over roughly the last 1, 5 and 15 minutes.",
      "No. Tasks blocked in uninterruptible I/O also raise load, so high load can occur with low CPU utilization. Check process states, I/O wait and storage or network filesystems.",
      "Use top, pidstat or ps -eo pid,ppid,cmd,%cpu --sort=-%cpu. Confirm whether one process, many processes or individual threads are responsible before taking action.",
      "I/O wait is CPU time during which the CPU has no runnable work while outstanding block I/O exists. A high value is a clue, not proof, of storage latency or pressure."
    ],

    "ssh.html": [
      "SSH is an encrypted protocol for remote login, command execution, file transfer and tunneling over an untrusted network.",
      "SSH commonly listens on TCP port 22, although administrators can configure another port.",
      "The client proves possession of a private key by signing authentication data. The server verifies it against the matching public key in an authorized source; the private key is never sent.",
      "A private key is the secret half of an asymmetric key pair. Protect it with strict permissions, a passphrase and secure storage, and rotate it if exposed.",
      "A public key is the shareable half of the pair. Servers use it to verify signatures created by the corresponding private key.",
      "authorized_keys is the per-user server file listing public keys allowed to authenticate, optionally with restrictions such as source addresses or forced commands.",
      "known_hosts stores host keys previously seen for servers. It lets the client detect an unexpected server identity change.",
      "Host verification helps prevent man-in-the-middle attacks. An unexpected key change must be validated through a trusted channel before the stored key is replaced.",
      "~/.ssh/config stores per-host client settings such as hostname, user, port, identity file, proxy jump and aliases, reducing repeated command options.",
      "sshd_config is the OpenSSH server configuration. Validate effective settings with sshd -T and syntax with sshd -t before a safe reload.",
      "Run ssh -vvv USER@HOST, identify whether failure is DNS, route, TCP, host verification or authentication, and correlate with server journal logs when you have alternate access.",
      "ssh -vvv enables maximum standard client debug verbosity, showing configuration selection, connection setup, key exchange and authentication attempts. Avoid sharing logs without checking for sensitive metadata.",
      "Use sudo ss -ltnp | grep ':22' and systemctl status ssh or sshd. Confirm the configured ListenAddress and Port with sshd -T.",
      "SCP copies files over an SSH connection. Modern OpenSSH implementations commonly use the SFTP protocol internally while preserving scp command behavior.",
      "SFTP is an SSH subsystem for interactive or automated file operations. It is not FTP over SSH.",
      "An SSH agent holds unlocked private keys in memory and answers signing requests so applications can authenticate without repeatedly reading key files or passphrases.",
      "SSH tunneling forwards TCP connections through an encrypted SSH session. Local, remote and dynamic forwards cover different source and destination arrangements.",
      "A bastion host is a hardened, controlled entry point used to reach systems that are not directly exposed. Access and activity should be tightly limited and audited.",
      "A jump host is an intermediate SSH host used with ProxyJump or -J to reach a final host. It is often implemented as a bastion.",
      "Confirm the hostname and port, then verify sshd is running and listening on the correct address. Check host firewall, cloud rules and whether a rejecting device sits in the path.",
      "Test DNS and route, use nc -vz HOST PORT or ssh -vvv, and inspect local, network and cloud firewalls for dropped traffic. Also verify return routing and server availability.",
      "Use ssh -vvv to see offered keys, confirm the correct username and IdentityFile, check agent keys, and validate ownership and permissions for the home directory, .ssh and authorized_keys. Then inspect server authentication logs and security-policy denials.",
      "Stop and verify the new fingerprint through a trusted source or console. Determine whether the host was legitimately rebuilt or rekeyed; do not blindly remove the old known_hosts entry because the change may indicate interception."
    ],

    "files-text.html": [
      "A pipe connects one command's standard output to the next command's standard input, allowing small tools to be composed into a processing pipeline.",
      "stdout is the normal output stream on file descriptor 1. stderr is the diagnostic stream on file descriptor 2, so it can be redirected independently.",
      "grep searches content for matching text or patterns. find walks directory trees and selects filesystem entries by name, type, size, time and other metadata.",
      "Use grep -R --line-number 'PATTERN' DIRECTORY. Add --include or --exclude to limit files and use -F when the pattern should be treated literally.",
      "Use find /path -type f -size +100M -print. Add -xdev if the search must stay on one filesystem.",
      "awk is commonly used for field-based text processing, filtering, calculations and report formatting.",
      "sed is a stream editor commonly used for substitutions, line selection and simple non-interactive text transformations.",
      "xargs builds command arguments from standard input. Use null-delimited input and xargs -0 with filenames to safely handle spaces and newlines.",
      "Use tail -F /path/to/log to follow a text log across rotation, or journalctl -f -u SERVICE for a systemd service.",
      "For a common access-log format: awk '{print $1}' access.log | sort | uniq -c | sort -nr. Validate that the first field is actually the client IP for that log format.",
      "> creates or truncates a file before writing output. >> appends output to the end, creating the file if necessary.",
      "2>&1 redirects file descriptor 2 to the destination currently used by file descriptor 1. Redirection order matters because descriptors are evaluated left to right."
    ],

    "environment.html": [
      "An environment variable is a named string value attached to a process and inherited by child processes. Programs use it for configuration such as locale, paths and endpoints.",
      "PATH is an ordered colon-separated list of directories the shell searches when a command name contains no slash. The first matching executable wins.",
      "export marks a shell variable for inclusion in the environment of future child processes. It does not change already-running processes or the parent process.",
      "The script may have a different PATH, working directory, user, shell or environment, especially under cron or systemd. Use absolute paths, declare dependencies and log the effective context.",
      "At process creation, the parent passes an environment to the child through the exec interface. The child receives a copy and later changes do not flow back to the parent."
    ]
  };

  const page = window.location.pathname.split("/").pop() || "";

  function createQuestion(question, answer, number) {
    const details = document.createElement("details");
    details.className = "interview-qa";

    const summary = document.createElement("summary");

    const badge = document.createElement("span");
    badge.className = "interview-question-number";
    badge.textContent = "Q" + number;

    const questionText = document.createElement("span");
    questionText.className = "interview-question-text";
    questionText.textContent = question;

    const label = document.createElement("span");
    label.className = "interview-answer-label";
    label.textContent = "Show answer";

    summary.append(badge, questionText, label);

    const answerBox = document.createElement("div");
    answerBox.className = "interview-answer";

    if (typeof answer === "string") {
      const paragraph = document.createElement("p");
      paragraph.textContent = answer;
      answerBox.appendChild(paragraph);
    } else if (answer) {
      answerBox.appendChild(answer);
    }

    details.append(summary, answerBox);
    details.addEventListener("toggle", function () {
      label.textContent = details.open ? "Hide answer" : "Show answer";
    });

    return details;
  }

  function createToolbar(list) {
    const toolbar = document.createElement("div");
    toolbar.className = "interview-answer-toolbar";

    const help = document.createElement("p");
    help.innerHTML =
      '<i class="bi bi-lightbulb" aria-hidden="true"></i>' +
      " Answer each question yourself first, then reveal the model answer.";

    const actions = document.createElement("div");
    actions.className = "interview-answer-actions";

    [
      ["Show all answers", true],
      ["Hide all answers", false]
    ].forEach(function (item) {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "secondary-button";
      button.textContent = item[0];
      button.addEventListener("click", function () {
        list.querySelectorAll(".interview-qa").forEach(function (details) {
          details.open = item[1];
        });
      });
      actions.appendChild(button);
    });

    toolbar.append(help, actions);
    return toolbar;
  }

  function findInterviewSection() {
    const heading = Array.from(document.querySelectorAll("h2")).find(
      function (candidate) {
        return /interview questions/i.test(candidate.textContent);
      }
    );

    if (!heading) return null;

    return {
      heading: heading,
      container:
        heading.closest(".card, .section, section") || heading.parentElement
    };
  }

  function enhanceQuestionList(section, answers) {
    const list = section.container.querySelector("ol");
    if (!list) return false;

    const questions = Array.from(list.children).filter(function (item) {
      return item.tagName === "LI";
    });

    if (!answers || questions.length !== answers.length) {
      console.warn(
        "Interview answer count mismatch for " + page,
        questions.length,
        answers ? answers.length : 0
      );
      return false;
    }

    const qaList = document.createElement("div");
    qaList.className = "interview-qa-list";

    questions.forEach(function (question, index) {
      qaList.appendChild(
        createQuestion(question.textContent.trim(), answers[index], index + 1)
      );
    });

    list.replaceWith(qaList);
    section.heading.insertAdjacentElement("afterend", createToolbar(qaList));
    return true;
  }

  function enhanceExistingAnswers(section) {
    const children = Array.from(section.container.children);
    const headingIndex = children.indexOf(section.heading);
    const questionHeadings = children.slice(headingIndex + 1).filter(function (node) {
      return node.tagName === "H3";
    });

    if (!questionHeadings.length) return false;

    const qaList = document.createElement("div");
    qaList.className = "interview-qa-list";

    questionHeadings.forEach(function (questionHeading, index) {
      const answerFragment = document.createDocumentFragment();
      let next = questionHeading.nextElementSibling;

      while (next && next.tagName !== "H3" && next.tagName !== "H2") {
        const current = next;
        next = next.nextElementSibling;
        answerFragment.appendChild(current);
      }

      const wrapper = document.createElement("div");
      wrapper.appendChild(answerFragment);
      qaList.appendChild(
        createQuestion(questionHeading.textContent.trim(), wrapper, index + 1)
      );
      questionHeading.remove();
    });

    section.container.appendChild(qaList);
    section.heading.insertAdjacentElement("afterend", createToolbar(qaList));
    return true;
  }

  function enhanceInterviewAnswers() {
    if (document.body.dataset.interviewAnswersReady === "true") return;

    const section = findInterviewSection();
    if (!section) return;

    const enhanced = answersByPage[page]
      ? enhanceQuestionList(section, answersByPage[page])
      : enhanceExistingAnswers(section);

    if (enhanced) {
      section.container.classList.add("interview-answer-card");
      document.body.dataset.interviewAnswersReady = "true";
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", enhanceInterviewAnswers);
  } else {
    enhanceInterviewAnswers();
  }
})();
