window.DEVOPS_INTEGRATION={
lifecycle:[['PLAN','GitHub Issues / GitLab Issues / Jira'],['CODE','Git + GitHub/GitLab/Bitbucket'],['BUILD','Maven / Gradle / npm / pip'],['TEST','Unit tests + SonarQube + dependency scans'],['CI','Jenkins / GitHub Actions / GitLab CI / Azure Pipelines'],['PACKAGE','Docker / Podman / Buildah'],['STORE','Harbor / GHCR / ECR / ACR / Artifact Registry / Nexus / Artifactory'],['INFRA','Terraform / OpenTofu / CloudFormation / Bicep / Pulumi'],['CONFIG','Ansible / Puppet / Chef / Salt'],['DEPLOY','Kubernetes / OpenShift'],['PACKAGE K8S','Helm / Kustomize'],['GITOPS','Argo CD / Flux'],['OBSERVE','Prometheus / Grafana / Datadog / New Relic'],['LOG','Loki / ELK / OpenSearch / Fluent Bit'],['TRACE','OpenTelemetry / Tempo / Jaeger'],['SECURITY','Trivy / SonarQube / Vault / OPA / Kyverno / Falco'],['RELIABILITY','SRE / SLO / incidents / chaos / capacity'],['PLATFORM','Backstage / golden paths / self-service'],['COST','FinOps / Kubecost / cloud cost management']],
comparisons:[
{a:'Docker',b:'Podman',useA:'Choose Docker when its ecosystem, Docker Desktop/Engine workflows and broad team familiarity are useful.',useB:'Choose Podman when daemonless/rootless workflows and Red Hat/container-tools integration fit better.',shared:'Both work with OCI images/containers and registries.'},
{a:'Jenkins',b:'GitHub Actions',useA:'Choose Jenkins for highly customizable self-managed pipelines, plugins and heterogeneous agents.',useB:'Choose GitHub Actions for repository-native event automation and lower platform overhead when code is on GitHub.',shared:'Both can test, build, scan, publish and deploy.'},
{a:'GitHub Actions',b:'GitLab CI/CD',useA:'Best when GitHub is the source platform and repository events/environments drive automation.',useB:'Best when GitLab is the integrated source, registry, runner and deployment platform.',shared:'Both use YAML pipelines, runners, artifacts, variables and deployment controls.'},
{a:'Terraform',b:'Ansible',useA:'Terraform creates/deletes declarative infrastructure and tracks resource state.',useB:'Ansible configures operating systems/apps and runs agentless operational tasks.',shared:'They often work together: Terraform creates servers, Ansible configures them.'},
{a:'Terraform',b:'CloudFormation',useA:'Terraform is useful for a common IaC workflow across many providers.',useB:'CloudFormation is AWS-native and tightly integrated with AWS resources and IAM.',shared:'Both declaratively provision infrastructure and support change previews.'},
{a:'Argo CD',b:'Jenkins',useA:'Argo CD continuously reconciles Kubernetes desired state from Git.',useB:'Jenkins executes general CI/CD jobs and can push deployment changes.',shared:'A common architecture is Jenkins builds the artifact; Argo CD deploys from Git.'},
{a:'Kubernetes',b:'Docker',useA:'Kubernetes manages many containers across nodes with scheduling, self-healing and service APIs.',useB:'Docker builds images and runs containers; it is simpler for single-host/local workloads.',shared:'Kubernetes runs container images built by Docker/other OCI builders.'},
{a:'AWS',b:'Azure',c:'Google Cloud',useA:'AWS offers a very broad service portfolio and mature cloud ecosystem.',useB:'Azure integrates strongly with Microsoft identity, enterprise and Windows ecosystems.',useC:'Google Cloud is strong in data, Kubernetes heritage and cloud-native managed services.',shared:'Choose from workload fit, organization skills, compliance, region/service availability and cost—not brand alone.'},
{a:'Helm',b:'Kustomize',useA:'Helm packages applications and uses templates/values with release history.',useB:'Kustomize overlays plain YAML without a template language.',shared:'Both can be rendered/deployed by Argo CD and are often used for environment-specific Kubernetes configuration.'},
{a:'Prometheus',b:'Grafana',useA:'Prometheus collects/stores metrics and evaluates PromQL/rules.',useB:'Grafana visualizes data from Prometheus and many other sources.',shared:'They are complementary, not direct replacements.'}
],
architectures:[
{title:'Basic CI/CD',flow:['Developer','GitHub','Jenkins','Docker','Registry','Linux Server']},
{title:'Kubernetes CI/CD',flow:['Developer','GitHub','GitHub Actions','Docker','Registry','Kubernetes','Helm']},
{title:'GitOps',flow:['Developer','Git','CI','Registry','GitOps Repo','Argo CD','Kubernetes']},
{title:'Complete Cloud',flow:['Git','CI','SonarQube/Trivy','Registry','Terraform','Cloud Kubernetes','Helm','Argo CD','Prometheus/Grafana']},
{title:'Multi-Cloud',flow:['Git','CI','Terraform','AWS/Azure/GCP','EKS/AKS/GKE','Argo CD','OpenTelemetry/Grafana']}
],
requestPath:['User','DNS','CDN/WAF','Cloud Load Balancer','Ingress/Gateway','Kubernetes Service','Pod','Application','Database/Cache'],
deployPath:['Developer','Git commit','PR/MR','CI tests/scans','Image build','Registry','GitOps config update','Argo CD/Flux','Kubernetes rollout','Health checks','Observability'],
failureChain:['Application down','Pod state','Container logs','Config/Secret','Service endpoints','Ingress/Gateway','DNS','Network policy/CNI','Cloud load balancer','Cloud network/IAM','Infrastructure state'],
roles:[['Developer','Application code, tests, container build inputs'],['DevOps Engineer','CI/CD, automation, deployments, operational workflows'],['Platform Engineer','Shared platform, golden paths, self-service, Kubernetes/IaC'],['SRE','Reliability, SLOs, incidents, capacity and production readiness'],['Security/DevSecOps','Supply chain, secrets, policy, vulnerabilities and runtime controls'],['Cloud Engineer','Landing zones, identity, networking, managed cloud services'],['DBA/Data Engineer','Databases, storage, backup, replication and data reliability']],
operations:[['Day 0 — Design','Architecture, requirements, security model, IaC, capacity and platform selection'],['Day 1 — Build/Launch','Provision infrastructure, configure services, deploy application, validate and document'],['Day 2 — Operate','Monitor, patch, scale, troubleshoot, backup, restore, upgrade, optimize cost and reliability']]
};